name: build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/FUNDING.YML'
      - '.github/dependabot.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/*.md'
      - '.gitconfig'
      - '.gitignore'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - '*.bat'
      - '.npmignore'
      - '.circleci/*'
      - 'README.md'

  push:
    paths-ignore:
      - '.github/FUNDING.YML'
      - '.github/dependabot.yml'
      - '.github/Issue_TEMPLATE/**'
      - '**/*.md'
      - '.gitconfig'
      - '.gitignore'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - '*.bat'
      - '.npmignore'
      - '.circleci/*'
      - 'README.md'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: windows-2025
#    strategy:
#      matrix:
#        os: [ 'windows-2025']
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Cache NuGet
#        uses: actions/cache@v4
#        with:
#          path: ~/.nuget/packages
#          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
#          restore-keys: |
#            ${{ runner.os }}-nuget-
      
      - name: Read package.json
        uses: actions/github-script@v7
        id: electron-version
        with:
          result-encoding: string
          script: |
            try {
              const fs = require('fs')
              const jsonString = fs.readFileSync('ElectronSharp.Host/package.json')
              var json = JSON.parse(jsonString);
              core.exportVariable('electron_version', json.devDependencies.electron.toString())
              core.notice("Building electron-sharp for Electron " + json.devDependencies.electron.toString())
            } catch(err) {
              core.error("Error while reading or parsing package.json")
              core.setFailed(err)
            }

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x' 

      - name: Install NPM dependencies
        run: |
          cd ./ElectronSharp.Host
          npm install --no-audit
          npm install -g typescript
          
          
      - name: tsc build
        run: |
          cd ./ElectronSharp.Host
          tsc
    
      - name: dotnet build
        run: dotnet build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-sharp-${{ env.electron_version}}
          path: |
            artifacts
