name: publish

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PackageVersion: 37.6.1.${{ github.run_id }}
  projectAPI:  './ElectronSharp.API/ElectronSharp.API.csproj'
  projectCLI:  './ElectronSharp.CLI/ElectronSharp.CLI.csproj'

jobs:
  build:
    runs-on: windows-2025
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x' 

      - name: Install NPM dependencies
        run: |
          cd ./ElectronSharp.Host
          npm install --no-audit
          
      - name: tsc build
        run: |
          cd ./ElectronSharp.Host
          tsc
    
      - name: build API
        run: dotnet build ${{env.projectAPI}} -c Release --force /property:Version=${{env.PackageVersion}}
        
      - name: build CLI
        run: dotnet build ${{env.projectCLI}} -c Release --force /property:Version=${{env.PackageVersion}}

        # TODO: Add dotnet publish
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-sharp-${{env.PackageVersion}}
          path: |
            artifacts
